/* -------------------------------------------------------------------------- */
/* This is meant to be used with                                              */
/* https://www.bottlecaps.de/rr/ui                                            */
/* to visualize the command syntax                                            */
/* -------------------------------------------------------------------------- */

/* -------------------------------------------------------------------------- */
/* Just the basic user characters                                             */
/* -------------------------------------------------------------------------- */

NEWLINE    ::= '\n'
TERMINATOR ::= NEWLINE
ALPHA      ::= ([a-z] | [A-Z] | '_')
DIGIT      ::= [0-9]
NUMBER     ::= DIGIT+ ('.' DIGIT+)?
ALPHANUMERIC ::= ALPHA | NUMBER
SPACE ::= ' '
WORD ::= ALPHA+
PRINTABLE  ::= ALPHANUMERIC | SPACE

/* -------------------------------------------------------------------------- */
/* Enumerations, basically                                                    */
/* -------------------------------------------------------------------------- */

DIRECTION ::= (
    n  | north     |
    ne | northeast |
    e  | east      |
    se | southeast |
    s  | south     |
    sw | southwest |
    w  | west      |
    nw | northwest |
    u  | up        |
    d  | down      |
    i  | in        |
    o  | out
)

/* -------------------------------------------------------------------------- */
/* Terms commonly used as shorthand for things in interpreter                 */
/* -------------------------------------------------------------------------- */

/* objects which exist */
NAME ::= WORD (SPACE WORD)*

/* alias with intention behind it */
ITEM ::= NAME 

/* -------------------------------------------------------------------------- */
/* Reoccuring clauses in interpreter                                          */
/* -------------------------------------------------------------------------- */

/* Suffix clause, used to indicate what item to use for given task */
WithClause ::= 'with' ITEM

/* -------------------------------------------------------------------------- */
/* Actual interpreter commands                                                */
/* -------------------------------------------------------------------------- */

/* Drop an item */
DropCommand      ::= ('d' | 'drop') ITEM

/* Pick up an item */ 
GetCommand       ::= ('g' | 'get')  ITEM

/* print command help */
HelpCommand      ::= 'help'

/* list inventory */
InventoryCommand ::= ('i' | 'inventory')

/* Attempt to lock passage to a given direction */
LockCommand      ::= 'lock' DIRECTION (WITH ITEM)?

/* look at current environment */
LookCommand      ::= ('l' | 'look')

/* attempt to move in a given direction */
MoveCommand      ::= ('go' DIRECTION) | DIRECTION

/* just repeats what its told */ 
PrintCommand     ::= ("echo" | "print") WORD (SPACE WORD)*

/* attempt to unlock passage to a given direction */
UnlockCommand    ::= 'unlock' DIRECTION (WITH ITEM)?

/* Debug - teleport to a given room index */
TeleportCommand  ::= 'teleport' INT

/* -------------------------------------------------------------------------- */
/* Collections for clarity sake in the interpreter                            */
/* -------------------------------------------------------------------------- */

/* commands the player can run at will */
PlayerCommands ::=          (
                                DropCommand         |
                                GetCommand          |
                                HelpCommand         |
                                InventoryCommand    |
                                LockCommand         |
                                LookCommand         |
                                MoveCommand         |
                                PrintCommand        |
                                UnlockCommand
                            )

/* Commands only available in debug mode */
DebugCommands ::=           (
                                TeleportExpression
                            )

/* -------------------------------------------------------------------------- */
/* Collections for clarity sake in the interpreter                            */
/* -------------------------------------------------------------------------- */
Commands ::= PlayerCommands | DebugCommands